module.exports = {
"ENSRegistry": require('./ENSRegistry.js').default,
"MerkleProofWrapper": require('./MerkleProofWrapper.js').default,
"TestToken": require('./TestToken.js').default,
"ENS": require('./ENS.js').default,
"ERC20Receiver": require('./ERC20Receiver.js').default,
"MessageSigned": require('./MessageSigned.js').default,
"Controlled": require('./Controlled.js').default,
"ApproveAndCallFallBack": require('./ApproveAndCallFallBack.js').default,
"ERC20Token": require('./ERC20Token.js').default,
"Owned": require('./Owned.js').default,
"StandardToken": require('./StandardToken.js').default,
"MerkleProof": require('./MerkleProof.js').default,
"SafeMath": require('./SafeMath.js').default,
"ResolverInterface": require('./ResolverInterface.js').default,
"PublicResolver": require('./PublicResolver.js').default,
"UsernameRegistrar": require('./UsernameRegistrar.js').default,
};